In [28]:
import pandas as pd
import numpy as np
df=pd.read_excel("MARKLIST.xlsx")
subjects = ['TOC', 'BE', 'DRL', 'AIR', 'GM', 'PROJECT', 'INDUSTRIAL VISIT TRAINING ']
grade_map = {'S': 100, 'A': 90, 'B': 80, 'C': 70, 'D': 60, 'E': 50, 'F': 40}
fail_grades = ['E', 'F']
df.head()

,SNO,REG_NO,STUDENT_NAME,TOC,BE,DRL,AIR,GM,PROJECT,INDUSTRIAL VISIT TRAINING,TOTAL
0,1,22TN0001,AARTHY.S,B,B,B,A,A,S,S,NaN
1,2,22TN0002,ABBIREDDY VINAY,D,C,C,B,E,S,S,NaN
2,3,22TN0006,ADITYA .R,C,B,B,A,S,B,S,NaN
3,4,22TN0009,AKASH.S,A,B,B,B,B,B,S,NaN
4,5,22TN0011,ANBU.J,A,A,B,C,B,S,S,NaN

In [28]:
import pandas as pd
import numpy as np
df=pd.read_excel("MARKLIST.xlsx")
subjects = ['TOC', 'BE', 'DRL', 'AIR', 'GM', 'PROJECT', 'INDUSTRIAL VISIT TRAINING ']
grade_map = {'S': 100, 'A': 90, 'B': 80, 'C': 70, 'D': 60, 'E': 50, 'F': 40}
fail_grades = ['E', 'F']
df.head()

,SNO,REG_NO,STUDENT_NAME,TOC,BE,DRL,AIR,GM,PROJECT,INDUSTRIAL VISIT TRAINING,TOTAL
0,1,22TN0001,AARTHY.S,B,B,B,A,A,S,S,NaN
1,2,22TN0002,ABBIREDDY VINAY,D,C,C,B,E,S,S,NaN
2,3,22TN0006,ADITYA .R,C,B,B,A,S,B,S,NaN
3,4,22TN0009,AKASH.S,A,B,B,B,B,B,S,NaN
4,5,22TN0011,ANBU.J,A,A,B,C,B,S,S,NaN

In [29]:
for sub in subjects:
    df[sub + '_num'] = df[sub].map(grade_map)
df['Average'] = df[[s + '_num' for s in subjects]].mean(axis=1)
def to_letter(score):
    if score >= 95: return 'S'
    elif score >= 85: return 'A'
    elif score >= 75: return 'B'
    elif score >= 65: return 'C'
    elif score >= 55: return 'D'
    else: return 'E'

df['Avg_Grade'] = df['Average'].apply(to_letter)
df['Has_Fail'] = df[subjects].apply(
    lambda row: any(g in fail_grades for g in row if pd.notna(g)), 
    axis=1
)
df['Result'] = df.apply(
    lambda r: f"FAIL (Avg: {r['Avg_Grade']})" if r['Has_Fail'] else f"PASS (Avg: {r['Avg_Grade']})", 
    axis=1
)

In [30]:
result = df[['SNO', 'REG_NO', 'STUDENT_NAME', 'Average', 'Avg_Grade', 'Has_Fail', 'Result']]
print(result.to_string(index=False))

 SNO   REG_NO             STUDENT_NAME   Average Avg_Grade  Has_Fail        Result
   1 22TN0001                 AARTHY.S 88.571429         A     False PASS (Avg: A)
   2 22TN0002          ABBIREDDY VINAY 75.714286         B      True FAIL (Avg: B)
   3 22TN0006                ADITYA .R 85.714286         A     False PASS (Avg: A)
   4 22TN0009                  AKASH.S 84.285714         B     False PASS (Avg: B)
   5 22TN0011                   ANBU.J 87.142857         A     False PASS (Avg: A)
   6 22TN0014             ARSULINGAM.T 84.285714         B     False PASS (Avg: B)
   7 22TN0017                 BALAJI.R 58.571429         D      True FAIL (Avg: D)
   8 22TN0018          BHARATHIDASAN.S 80.000000         B      True FAIL (Avg: B)
   9 22TN0021              CHANDIRAN.S 84.285714         B     False PASS (Avg: B)
  10 22TN0024                 DEEPAK.K 81.428571         B     False PASS (Avg: B)
  11 22TN0027               DHAYALAN.B 82.857143         B     False PASS (Avg: B)
  12 22TN0029                DHIVYAA.S 90.000000         A     False PASS (Avg: A)
  13 22TN0030           DINESHKUMAR .M 82.857143         B     False PASS (Avg: B)
  14 22TN0032                GAUDHAM.R 77.142857         B      True FAIL (Avg: B)
  15 22TN0033              GOKULNATH.K 71.428571         C      True FAIL (Avg: C)
  16 22TN0035          HARIDHARSHINI.S 81.428571         B     False PASS (Avg: B)
  17 22TN0036                 HARINI.K 90.000000         A     False PASS (Avg: A)
  18 22TN0038              HARIPRIYA.I 88.571429         A     False PASS (Avg: A)
  19 22TN0039               HARYSHWA.S 74.285714         C      True FAIL (Avg: C)
  20 22TN0041              HEMALATHA.M 90.000000         A     False PASS (Avg: A)
  21 22TN0045         JEEVAGANABATHY.K 74.285714         C      True FAIL (Avg: C)
  22 22TN0047 JEFRINA MARY CATCHIRAYAR 80.000000         B     False PASS (Avg: B)
  23 22TN0048             JEGANATHAN.I 75.714286         B      True FAIL (Avg: B)
  24 22TN0055        KENCY SEROPHINE.E 85.714286         A     False PASS (Avg: A)
  25 22TN0057                KISHORE.M 74.285714         C      True FAIL (Avg: C)
  26 22TN0060                LAKSHMI.R 84.285714         B     False PASS (Avg: B)
  27 22TN0063            LOKESHWARAN.S 87.142857         A     False PASS (Avg: A)
  28 22TN0065               MADANRAJ.M 75.714286         B     False PASS (Avg: B)
  29 22TN0067          MAHAA POORANI.S 84.285714         B     False PASS (Avg: B)
  30 22TN0068             MANIKANDAN.R 85.714286         A     False PASS (Avg: A)
  31 22TN0069         MOHAMAD SIDDIQ.S 62.857143         D      True FAIL (Avg: D)
  32 22TN0070               MOHANRAJ.K 72.857143         C      True FAIL (Avg: C)
  33 22TN0074                 NAFISA.F 82.857143         B     False PASS (Avg: B)
  34 22TN0075               NANDHINI.S 80.000000         B      True FAIL (Avg: B)
  35 22TN0077           NAVIN ROSHAN.S 81.428571         B     False PASS (Avg: B)
  36 22TN0079                 NUHANA.A 87.142857         A     False PASS (Avg: A)
  37 22TN0080            PAVAN KUMAR.P 72.857143         C     False PASS (Avg: C)
  38 22TN0081            PRABHAVATHI.M 77.142857         B     False PASS (Avg: B)
  39 22TN0082          PRAVEEN KUMAR.D 84.285714         B     False PASS (Avg: B)
  40 22TN0083               PREMNATH.K 81.428571         B     False PASS (Avg: B)
  41 22TN0084              PUVIRAJAN.P 87.142857         A     False PASS (Avg: A)
  42 22TN0086                  RAFAN.A 70.000000         C      True FAIL (Avg: C)
  43 22TN0090             RAVIRAGHAV.S 78.571429         B      True FAIL (Avg: B)
  44 22TN0091               RISABHAN.A 82.857143         B     False PASS (Avg: B)
  45 22TN0092            RUTHRAPATHI.P 90.000000         A     False PASS (Avg: A)
  46 22TN0095               SANTHIYA.P 92.857143         A     False PASS (Avg: A)
  47 22TN0097              SARUKESH .G 71.428571         C      True FAIL (Avg: C)
  48 22TN0098                SATHISH.S 72.857143         C      True FAIL (Avg: C)
  49 22TN0099                 SHAAM .T 70.000000         C      True FAIL (Avg: C)
  50 22TN0101               SIDDARTH.M 57.142857         D      True FAIL (Avg: D)
  51 22TN0105               SUCHITRA.S 88.571429         A     False PASS (Avg: A)
  52 22TN0106             SUDHARSHAN.S 71.428571         C      True FAIL (Avg: C)
  53 22TN0108               THEEBIGA.T 85.714286         A     False PASS (Avg: A)
  54 22TN0109           THILAKESHWAR.S 77.142857         B      True FAIL (Avg: B)
  55 22TN0110             TILAKKUMAR.R 77.142857         B      True FAIL (Avg: B)
  56 22TN0112               VARUNRAJ.M 74.285714         C      True FAIL (Avg: C)
  57 22TN0113      VENGAUDARAMANAN.G S 77.142857         B     False PASS (Avg: B)
  58 22TN0114        VENKADAKRISHNAN.J 88.571429         A     False PASS (Avg: A)
  59 22TN0117         VISHNU VARDHAN.R 70.000000         C      True FAIL (Avg: C)

In [38]:
df['TOTAL'] = df['Avg_Grade']
df['FAILED?'] = df['Has_Fail'].map({True: 'Y', False: 'N'})

print("✅ TOTAL and FAILED? columns added!")

✅ TOTAL and FAILED? columns added!

In [37]:
grade_order = {'S': 0, 'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5}
df['Grade_Sort'] = df['TOTAL'].map(grade_order)
df['Fail_Sort'] = df['FAILED?'].map({'N': 0, 'Y': 1})
df = df.sort_values(by=['Fail_Sort', 'Grade_Sort', 'Average'], ascending=[True, True, False])
df = df.reset_index(drop=True)
df['SNO'] = df.index + 1
result = df[['SNO', 'REG_NO', 'STUDENT_NAME', 'TOC', 'BE', 'DRL', 'AIR', 'GM', 
             'PROJECT', 'INDUSTRIAL VISIT TRAINING ', 'TOTAL', 'FAILED?']]
print(result.to_string(index=False))
df.to_excel("MARKLIST_FINAL.xlsx", index=False)
print("\n✅ Saved to MARKLIST_FINAL.xlsx")

 SNO   REG_NO             STUDENT_NAME TOC BE DRL AIR GM PROJECT INDUSTRIAL VISIT TRAINING  TOTAL FAILED?
   1 22TN0095               SANTHIYA.P   A  S   B   A  A       S                          S     A       N
   2 22TN0029                DHIVYAA.S   B  S   B   B  A       S                          S     A       N
   3 22TN0036                 HARINI.K   A  B   A   B  A       S                          S     A       N
   4 22TN0041              HEMALATHA.M   A  B   B   A  A       S                          S     A       N
   5 22TN0092            RUTHRAPATHI.P   A  A   B   A  B       S                          S     A       N
   6 22TN0001                 AARTHY.S   B  B   B   A  A       S                          S     A       N
   7 22TN0038              HARIPRIYA.I   A  B   B   B  A       S                          S     A       N
   8 22TN0105               SUCHITRA.S   B  B   A   A  B       S                          S     A       N
   9 22TN0114        VENKADAKRISHNAN.J   A  B   B   B  A       S                          S     A       N
  10 22TN0011                   ANBU.J   A  A   B   C  B       S                          S     A       N
  11 22TN0063            LOKESHWARAN.S   B  B   B   B  A       S                          S     A       N
  12 22TN0079                 NUHANA.A   B  B   B   A  A       A                          S     A       N
  13 22TN0084              PUVIRAJAN.P   B  A   A   C  B       S                          S     A       N
  14 22TN0006                ADITYA .R   C  B   B   A  S       B                          S     A       N
  15 22TN0055        KENCY SEROPHINE.E   A  B   B   B  C       S                          S     A       N
  16 22TN0068             MANIKANDAN.R   B  B   B   B  B       S                          S     A       N
  17 22TN0108               THEEBIGA.T   C  B   B   B  A       S                          S     A       N
  18 22TN0009                  AKASH.S   A  B   B   B  B       B                          S     B       N
  19 22TN0014             ARSULINGAM.T   B  B   B   B  C       S                          S     B       N
  20 22TN0021              CHANDIRAN.S   B  B   B   D  A       S                          S     B       N
  21 22TN0060                LAKSHMI.R   C  B   B   B  B       S                          S     B       N
  22 22TN0067          MAHAA POORANI.S   B  B   B   C  B       S                          S     B       N
  23 22TN0082          PRAVEEN KUMAR.D   B  C   B   B  B       S                          S     B       N
  24 22TN0027               DHAYALAN.B   B  A   B   C  A       C                          S     B       N
  25 22TN0030           DINESHKUMAR .M   C  B   B   C  B       S                          S     B       N
  26 22TN0074                 NAFISA.F   B  B   B   B  C       A                          S     B       N
  27 22TN0091               RISABHAN.A   C  A   B   B  D       S                          S     B       N
  28 22TN0024                 DEEPAK.K   D  C   B   B  B       S                          S     B       N
  29 22TN0035          HARIDHARSHINI.S   C  B   B   B  D       S                          S     B       N
  30 22TN0077           NAVIN ROSHAN.S   C  B   B   B  C       A                          S     B       N
  31 22TN0083               PREMNATH.K   C  B   B   B  D       S                          S     B       N
  32 22TN0047 JEFRINA MARY CATCHIRAYAR   B  C   D   B  C       S                          S     B       N
  33 22TN0081            PRABHAVATHI.M   C  C   C   C  C       A                          S     B       N
  34 22TN0113      VENGAUDARAMANAN.G S   C  D   B   B  B       C                          S     B       N
  35 22TN0065               MADANRAJ.M   D  B   C   C  C       B                          S     B       N
  36 22TN0080            PAVAN KUMAR.P   D  C   C   B  D       C                          S     C       N
  37 22TN0018          BHARATHIDASAN.S   C  B   B   E  B       S                          S     B       Y
  38 22TN0075               NANDHINI.S   E  B   B   C  B       S                          S     B       Y
  39 22TN0090             RAVIRAGHAV.S   B  C   B   C  E       S                          S     B       Y
  40 22TN0032                GAUDHAM.R   C  C   C   B  E       S                          S     B       Y
  41 22TN0109           THILAKESHWAR.S   E  C   C   B  C       S                          S     B       Y
  42 22TN0110             TILAKKUMAR.R   D  E   B   B  B       A                          S     B       Y
  43 22TN0002          ABBIREDDY VINAY   D  C   C   B  E       S                          S     B       Y
  44 22TN0048             JEGANATHAN.I   E  C   C   B  C       A                          S     B       Y
  45 22TN0039               HARYSHWA.S   E  C   C   C  B       B                          S     C       Y
  46 22TN0045         JEEVAGANABATHY.K   E  B   C   B  B       D                          S     C       Y
  47 22TN0057                KISHORE.M   E  C   C   B  C       B                          S     C       Y
  48 22TN0112               VARUNRAJ.M   E  D   B   B  B       C                          S     C       Y
  49 22TN0070               MOHANRAJ.K   D  B   C   C  E       B                          S     C       Y
  50 22TN0098                SATHISH.S   E  C   D   C  D       S                          S     C       Y
  51 22TN0033              GOKULNATH.K   D  C   C   C  E       B                          S     C       Y
  52 22TN0097              SARUKESH .G   E  C   C   C  C       C                          S     C       Y
  53 22TN0106             SUDHARSHAN.S   E  D   C   B  C       C                          S     C       Y
  54 22TN0086                  RAFAN.A   E  D   C   D  E       S                          S     C       Y
  55 22TN0099                 SHAAM .T   E  D   B   C  D       C                          S     C       Y
  56 22TN0117         VISHNU VARDHAN.R   F  B   D   D  B       C                          S     C       Y
  57 22TN0069         MOHAMAD SIDDIQ.S   F  C   C   C  E       F                          S     D       Y
  58 22TN0017                 BALAJI.R   E  E   D   E  E       E                          S     D       Y
  59 22TN0101               SIDDARTH.M   F  F   F   F  F       S                          S     D       Y

✅ Saved to MARKLIST_FINAL.xlsx